// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"greet/internal/logic"
	"greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: BaseHandlerFunc(serverCtx,logic.GreetLogic{}),//
			},
			{
				Method:  http.MethodGet,
				Path:    "/to/:name",
				Handler: BaseHandlerFunc(serverCtx,logic.CustomLogic{}),//
			},
		},
	)
}
